//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.Activities_Participation = new HashSet<Activities_Participation>();
            this.Testimonies = new HashSet<Testimony>();
        }

        [Display(Name = "ID")] public int Activity_ID { get; set; }
        [Required] [Display(Name = "Activity Name")] public string Activity_Name { get; set; }
        [Required] [Display(Name = "Sub-Product")] public int SubProductID { get; set; }
        [Required] [Display(Name = "Facilitator")] public int Facilitator1 { get; set; }
        [Display(Name = "Facilitator")] public Nullable<int> Facilitator2 { get; set; }
        [Display(Name = "Facilitator")] public Nullable<int> Facilitator3 { get; set; }
        [Display(Name = "Implementing Partner")] public int ImplementingPartnerID { get; set; }
        [Required] [Display(Name = "Location")] public int LocationID { get; set; }
        [Display(Name = "Project")] public Nullable<int> ProjectID { get; set; }
        [Required] [Display(Name = "Beneficiary Type")] public int BeneficiaryTypeID { get; set; }
        [Required] [Display(Name = "Starting Date")] [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)] public System.DateTime Starting_Date { get; set; }
        [Display(Name = "Ending Date")] [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)] public Nullable<System.DateTime> Ending_Date { get; set; }
        [Display(Name = "Other Details")] public string Activity_Details { get; set; }

        public IEnumerable<Sub_Products> Sub_Products_Collection { get; set; }
        public IEnumerable<Facilitator> Facilitator1_Collection { get; set; }
        public IEnumerable<Facilitator> Facilitator_Whole_Name_Collection { get; set; }
        public IEnumerable<Location> Location_Collection { get; set; }
        public IEnumerable<Organization> Implementing_Organization_Collection { get; set; }
        public IEnumerable<Project> Project_Collection { get; set; }
        public IEnumerable<Beneficiary_Types> Beneficiary_Type_Collection { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activities_Participation> Activities_Participation { get; set; }
        public virtual Beneficiary_Types Beneficiary_Types { get; set; }
        public virtual Facilitator Facilitator { get; set; }
        public virtual Facilitator Facilitator4 { get; set; }
        public virtual Facilitator Facilitator5 { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Location Location { get; set; }
        public virtual Project Project { get; set; }
        public virtual Sub_Products Sub_Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Testimony> Testimonies { get; set; }
    }
}
