//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entrena_QL_Database_Entities : DbContext
    {
        public Entrena_QL_Database_Entities()
            : base("name=Entrena_QL_Database_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Activities_Participation> Activities_Participation { get; set; }
        public virtual DbSet<Beneficiary_Types> Beneficiary_Types { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Facilitator> Facilitators { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Organizations_Relationship> Organizations_Relationship { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<Partnership_Types> Partnership_Types { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Sub_Products> Sub_Products { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Testimony> Testimonies { get; set; }
        public virtual DbSet<System_Users> System_Users { get; set; }
    }
}
