//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Facilitator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facilitator()
        {
            this.Activities = new HashSet<Activity>();
            this.Activities1 = new HashSet<Activity>();
            this.Activities2 = new HashSet<Activity>();
        }

        [Display(Name = "ID")] public int Facilitator_ID { get; set; }
        [Required] [Display(Name = "Facilitator Name")] public string Facilitator_Name { get; set; }
        [Required] [Display(Name = "Last Name")] public string Facilitator_Last_Name { get; set; }
        [Display(Name = "Facilitator Name")] public string Facilitator_Whole_Name { get { return Facilitator_Name + " " + Facilitator_Last_Name; } }
        [Display(Name = "Date of Birth")] [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)] public Nullable<System.DateTime> Facilitator_Date_Of_Birth { get; set; }
        [Required] [Display(Name = "Gender")] public int GenderID { get; set; }
        [Display(Name = "Phone")] public string Facilitator_Phone { get; set; }
        [Display(Name = "Email")] public string Facilitator_Email { get; set; }
        [Display(Name = "Registration Date")] [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)] public System.DateTime Facilitator_Registration_Date { get; set; }
        [Display(Name = "Biodata")] public string Facilitator_Biodata { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities2 { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Gender Gender1 { get; set; }
    }
}
