//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.Activities = new HashSet<Activity>();
        }

        [Display(Name = "ID")] public int Location_ID { get; set; }
        [Required] [Display(Name = "Province")] public int ProvinceID { get; set; }
        [Required] [Display(Name = "Location Name")] public string Location_Name { get; set; }
        [Display(Name = "Latitude")] public Nullable<double> Latitude { get; set; }
        [Display(Name = "Longitude")] public Nullable<double> Longitude { get; set; }
        [Display(Name = "Other Details")] public string Location_Details { get; set; }

        public IEnumerable<Province> Provinces_Collection { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual Province Province { get; set; }
    }
}
