//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Participants")]
    public partial class Participant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Participant()
        {
            this.Activities_Participation = new HashSet<Activities_Participation>();
            this.Testimonies = new HashSet<Testimony>();
        }

        [Display(Name = "ID")] public int Participant_ID { get; set; }
        [Required] [Display(Name = "Participant Name")] public string Participant_Name { get; set; }
        [Required] [Display(Name = "Last Name")] public string Participant_Last_Name { get; set; }
        [Display(Name = "Participant Name")] public string Participant_Whole_Name { get { return Participant_Name + " " + Participant_Last_Name; } }
        [Display(Name = "Date of Birth")] [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)] public Nullable<System.DateTime> Participant_Date_Of_Birth { get; set; }
        [Required] [Display(Name = "Gender")] public int GenderID { get; set; }
        [Display(Name = "Phone")] public string Participant_Phone { get; set; }
        [Display(Name = "Email")] public string Participant_Email { get; set; }
        [Display(Name = "Registration Date")] [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)] public System.DateTime Participant_Registration_Date { get; set; }
        [Display(Name = "Other Details")] public string Participant_Details { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activities_Participation> Activities_Participation { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Gender Gender1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Testimony> Testimonies { get; set; }
    }
}
