//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Partnership_Types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partnership_Types()
        {
            this.Organizations_Relationship = new HashSet<Organizations_Relationship>();
        }

        [Display(Name = "ID")] public int Partnership_Type_ID { get; set; }
        [Required] [Display(Name = "Partnership Type Name")] public string Partnership_Type_Name { get; set; }
        [Display(Name = "Other Details")] public string Partnership_Type_Details { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organizations_Relationship> Organizations_Relationship { get; set; }
    }
}
