//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Activities = new HashSet<Activity>();
        }

        [Display(Name = "ID")] public int Project_ID { get; set; }
        [Required] [Display(Name = "Project Name")] public string Project_Name { get; set; }
        [Required] [Display(Name = "Donor")] public int ProjectDonor1 { get; set; }
        [Display(Name = "Donor")] public Nullable<int> ProjectDonor2 { get; set; }
        [Display(Name = "Donor")] public Nullable<int> ProjectDonor3 { get; set; }
        [Display(Name = "Project Amount")] public Nullable<double> Project_Amount { get; set; }
        [Display(Name = "Other Details")] public string Project_Details { get; set; }

        public IEnumerable<Organization> Organizations_Collection { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Organization Organization1 { get; set; }
        public virtual Organization Organization2 { get; set; }
    }
}
