//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Testimony
    {
        [Display(Name = "ID")] public int Testimony_ID { get; set; }
        [Required] [Display(Name = "Activity")] public int ActivityID { get; set; }
        [Required] [Display(Name = "Participant")] public int ParticipantID { get; set; }
        [Display(Name = "Testimony")] public string Testimony_Details { get; set; }

        public IEnumerable<Participant> Participant_Collection { get; set; }
        public IEnumerable<Activity> Activities_Collection { get; set; }

        public virtual Activity Activity { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
